name: acofoodflutter
description: "Aplicación de seguimiento nutricional con integración de balanza inteligente y análisis detallado de macronutrientes, vitaminas y minerales."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.4.1+25

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_blue_plus: 1.32.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  intl: ^0.20.2
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  fl_chart: ^0.68.0
  share_plus: ^10.0.0
  file_picker: ^8.0.7
  pdf: ^3.11.1
  printing: ^5.13.2
  excel: ^4.0.3
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.2
  google_sign_in: ^6.2.2
  flutter_native_splash: ^2.3.0 
  
     
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:
  assets:
    - assets/icons/app_icon.png
    - assets/icons/splash_icon.png
    - assets/icons/splash_elements.png
  uses-material-design: true

flutter_native_splash:
  color: "#F0F8F3"
  image: assets/icons/splash_icon.png
  android: true
  ios: true
  android_12:
    color: "#F0F8F3"
    image: assets/icons/splash_icon.png